### ISSUE TITLE
Big files (10MB and more) are not synchronizing

### ISSUE THREAD

**Issue by defder-su** [ZeroNetX/ZeroNet#153] opened 2022-02-23 14:33 UTC
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.6 (rev4565)
  * Operating system: macOS 10.13
  * Tor status: always
  * Opened port: no

#### Steps to reproduce:

  1. Create site (don't use optional files).
  2. Add some big file (e.g. 15MB zip).
  3. Add some middle file (8MB zip).
  3. Sign and publish the site.
  4. Visit the site from some other ZeroNet node.

#### Observed Results:

  * The site opens, the middle file is available (maybe after some delay), but the big file is not found.

#### Expected Results:

  * The site should be fully synced.

**Comment by defder-su** [comment] 2022-02-23 18:59
Big optional files work (ZeroNet splits them automatically), but optional files are not durable.

**Comment by defder-su** [comment] 2022-02-26 13:01
Reproduced it with http://127.0.0.1:43110/1Pj7TzBUdQRk9T9mzPQBjv6ju5oBiLCtry/ (file archive). Almost all files (more than thousand) are successfully downloaded, except 35 big files.

**Comment by mx5kevin** [comment] 2022-03-16 11:57
This is a small part of the problem

-Not posible to download all large files simple way when a user download a single user zite.

- Help distribute added optional files option is hidden in the program and a preset limit makes the function unusable.

- It has to be set up in a complicated way the large files in the .json file. Without this the files what larger than 10MB inoperable. Based on type rather than size, the system should differentiate between optional and non-optional files automatically. htm, html, css, js, pictures, pdf, what the browser displays and you need the web page to look like it could all be a non-optional file by default. And all other files are optional by default. Offer the user a button to determine the size of all optional large files and download them all at once in single user zites. In single user sites can't watch a video, access attachments zip, pdf etc because the entire content of the website is not downloaded. And these are all parts of the website and the site owner intended them to be downloaded the users.

- A distinction should be made by single and multiuser zites. In single user zites all content is intended for download. If everyone does not download the full content, the site will be inaccessible and unenjoyable. The single user pages are designed to give users full content downloads. If B the user From A the (site owner not get the full content), C user from B will not possible to get the content. And it won't be C, D and E seeders. This is where the whole network fails!  In multiuser sites more users upload larger files and it is not intended to provide users with full content downloads.

-The incress site limit question: even if it is highlighted, larger and all optional files will not be downloaded. If not incressed, the page will not display correctly.

- The system will not start at system startup so who has the files many people does nott seed it.

-Using one click the system is unable to download the files, does not finish downloading files. If B the user From A the (site owner not get the full content), C user from B will not possible to get the content. And it won't be C, D and E seeders conception. This system is unable to finish downloading a file. The download will be interrupted for all larger files.

The P2P protocol and the engineering solution conflict. Until this network becomes Seeding centric where the most important From A the (content owner) B the user get all content. And user C get from B without A if a goes offline the content. Until then, this network will not work.

**Comment by mx5kevin** [comment] 2022-03-16 12:19
The problem is that the original developer did not see this network through the eyes of a website owner who using a PC, Laptop, and not a 24/7 running server. It looks like haven't been tested regularly in a live environment how it works with test pages. Anyone who sets up a website and tests from another network as user immediately see the serious problems. If the point B not get from A the content then how do you get it C from B? The other from the user's point of view is simple download. Most people can’t handle more complex options and don’t understand what it is. In single user zites download the full content default way (if someone doesn't need for the optional files than can turn it off if more competent, but the average user should not be disturbed by this). In multi user zites download the current content if the user click the same file. If someone wants to start a video, download a file don’t look at why it’s not available.

**Comment by defder-su** [comment] 2023-01-17 00:17
PR https://github.com/ZeroNetX/ZeroNet/pull/204

**Closed as completed** 2023-06-30 23:06 UTC

**Comment by defder-su** [comment] 2024-12-18 03:41
This issue is not resolved currently.
